-- pg_vault_tde--1.0--1.4.sql
-- Upgrade bridge: v1.0 → v1.4
--
-- Copyright (c) 2026 Miriade S.r.l. — PostgreSQL License
--
-- All v1.4 features (AppRole auth, secret_id rotation, rate limiting,
-- Kubernetes auth, OpenSSL 3.x provider, BGW token renewal) were built
-- into the base 1.0 SQL schema — there are no DDL changes at the SQL layer
-- between v1.0 and v1.4.  This script exists solely to register the
-- version step so that ALTER EXTENSION pg_vault_tde UPDATE TO '1.5' can
-- traverse the chain: 1.0 → 1.4 → 1.5.
--
-- No-op intentional.
