-- pg_vault_tde--1.6--1.7.sql
--
-- Migration from pg_vault_tde 1.6 to 1.7.
--
-- v1.7 — Per-Database KMS + pg_restore_tde
-- ─────────────────────────────────────────
-- Key changes in this release:
--
--   • All KMS GUCs changed from PGC_POSTMASTER to PGC_SUSET, enabling
--     per-database KMS configuration via ALTER DATABASE SET without restart.
--
--   • pg_restore_tde standalone binary: full decrypt-and-pipe restore loop
--     (reads tde_backup_header, unwraps DEK, decrypts block stream, pipes
--     to pg_restore -Fc).
--
-- No catalog schema changes are required for this upgrade; the migration
-- script is a no-op placeholder that satisfies the ALTER EXTENSION UPDATE
-- upgrade chain (1.0 → 1.4 → 1.5 → 1.6 → 1.7).
--
-- If future patches add SQL-visible objects (functions, types, tables),
-- add them here.
